version: '3.8'

services:
  backend:
    build:
      context: ./backend-server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
    networks:
      - mynetwork

  frontend:
    build:
      context: ./website
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
